# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapfileexportdlg.ui'
#
# Created: Wed Jan 21 23:00:59 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapfileExportDlg(object):
    def setupUi(self, MapfileExportDlg):
        MapfileExportDlg.setObjectName(_fromUtf8("MapfileExportDlg"))
        MapfileExportDlg.resize(814, 669)
        MapfileExportDlg.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(MapfileExportDlg)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(MapfileExportDlg)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.tabWiget = QtGui.QTabWidget(MapfileExportDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWiget.sizePolicy().hasHeightForWidth())
        self.tabWiget.setSizePolicy(sizePolicy)
        self.tabWiget.setObjectName(_fromUtf8("tabWiget"))
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabGeneral)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label6 = QtGui.QLabel(self.groupBox_2)
        self.label6.setMinimumSize(QtCore.QSize(80, 0))
        self.label6.setObjectName(_fromUtf8("label6"))
        self.gridLayout_4.addWidget(self.label6, 0, 0, 1, 1)
        self.txtGeneralWebServerUrl = QtGui.QLineEdit(self.groupBox_2)
        self.txtGeneralWebServerUrl.setText(_fromUtf8("http://localhost/cgi-bin/mapserv"))
        self.txtGeneralWebServerUrl.setObjectName(_fromUtf8("txtGeneralWebServerUrl"))
        self.gridLayout_4.addWidget(self.txtGeneralWebServerUrl, 0, 1, 1, 1)
        self.label6_5 = QtGui.QLabel(self.groupBox_2)
        self.label6_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label6_5.setObjectName(_fromUtf8("label6_5"))
        self.gridLayout_4.addWidget(self.label6_5, 1, 0, 1, 1)
        self.txtGeneralWebImagePath = QtGui.QLineEdit(self.groupBox_2)
        self.txtGeneralWebImagePath.setText(_fromUtf8(""))
        self.txtGeneralWebImagePath.setObjectName(_fromUtf8("txtGeneralWebImagePath"))
        self.gridLayout_4.addWidget(self.txtGeneralWebImagePath, 1, 1, 1, 1)
        self.label6_4 = QtGui.QLabel(self.groupBox_2)
        self.label6_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label6_4.setObjectName(_fromUtf8("label6_4"))
        self.gridLayout_4.addWidget(self.label6_4, 3, 0, 1, 1)
        self.label6_7 = QtGui.QLabel(self.groupBox_2)
        self.label6_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label6_7.setToolTip(_fromUtf8(""))
        self.label6_7.setObjectName(_fromUtf8("label6_7"))
        self.gridLayout_4.addWidget(self.label6_7, 4, 0, 1, 1)
        self.txtGeneralExternalGraphicRegexp = QtGui.QLineEdit(self.groupBox_2)
        self.txtGeneralExternalGraphicRegexp.setToolTip(_fromUtf8(""))
        self.txtGeneralExternalGraphicRegexp.setText(_fromUtf8(""))
        self.txtGeneralExternalGraphicRegexp.setObjectName(_fromUtf8("txtGeneralExternalGraphicRegexp"))
        self.gridLayout_4.addWidget(self.txtGeneralExternalGraphicRegexp, 4, 1, 1, 1)
        self.txtGeneralWebTempPath = QtGui.QLineEdit(self.groupBox_2)
        self.txtGeneralWebTempPath.setToolTip(_fromUtf8(""))
        self.txtGeneralWebTempPath.setText(_fromUtf8(""))
        self.txtGeneralWebTempPath.setObjectName(_fromUtf8("txtGeneralWebTempPath"))
        self.gridLayout_4.addWidget(self.txtGeneralWebTempPath, 3, 1, 1, 1)
        self.label6_6 = QtGui.QLabel(self.groupBox_2)
        self.label6_6.setMinimumSize(QtCore.QSize(80, 0))
        self.label6_6.setObjectName(_fromUtf8("label6_6"))
        self.gridLayout_4.addWidget(self.label6_6, 2, 0, 1, 1)
        self.txtGeneralWebImageUrl = QtGui.QLineEdit(self.groupBox_2)
        self.txtGeneralWebImageUrl.setText(_fromUtf8(""))
        self.txtGeneralWebImageUrl.setObjectName(_fromUtf8("txtGeneralWebImageUrl"))
        self.gridLayout_4.addWidget(self.txtGeneralWebImageUrl, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 3)
        self.grpMap = QtGui.QGroupBox(self.tabGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMap.sizePolicy().hasHeightForWidth())
        self.grpMap.setSizePolicy(sizePolicy)
        self.grpMap.setObjectName(_fromUtf8("grpMap"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpMap)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label5 = QtGui.QLabel(self.grpMap)
        self.label5.setIndent(20)
        self.label5.setObjectName(_fromUtf8("label5"))
        self.gridLayout_2.addWidget(self.label5, 0, 4, 1, 1)
        self.txtGeneralMapHeight = QtGui.QLineEdit(self.grpMap)
        self.txtGeneralMapHeight.setText(_fromUtf8("600"))
        self.txtGeneralMapHeight.setObjectName(_fromUtf8("txtGeneralMapHeight"))
        self.gridLayout_2.addWidget(self.txtGeneralMapHeight, 1, 3, 1, 1)
        self.label2 = QtGui.QLabel(self.grpMap)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout_2.addWidget(self.label2, 1, 0, 1, 1)
        self.txtGeneralMapProjLibFolder = QtGui.QLineEdit(self.grpMap)
        self.txtGeneralMapProjLibFolder.setObjectName(_fromUtf8("txtGeneralMapProjLibFolder"))
        self.gridLayout_2.addWidget(self.txtGeneralMapProjLibFolder, 2, 1, 1, 1)
        self.cmbGeneralMapUnits = QtGui.QComboBox(self.grpMap)
        self.cmbGeneralMapUnits.setEnabled(False)
        self.cmbGeneralMapUnits.setObjectName(_fromUtf8("cmbGeneralMapUnits"))
        self.gridLayout_2.addWidget(self.cmbGeneralMapUnits, 1, 5, 1, 1)
        self.txtGeneralMapName = QtGui.QLineEdit(self.grpMap)
        self.txtGeneralMapName.setToolTip(_fromUtf8(""))
        self.txtGeneralMapName.setText(_fromUtf8("QGIS-MAP"))
        self.txtGeneralMapName.setObjectName(_fromUtf8("txtGeneralMapName"))
        self.gridLayout_2.addWidget(self.txtGeneralMapName, 0, 1, 1, 3)
        self.label_9 = QtGui.QLabel(self.grpMap)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label4 = QtGui.QLabel(self.grpMap)
        self.label4.setEnabled(False)
        self.label4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.gridLayout_2.addWidget(self.label4, 1, 4, 1, 1)
        self.label3 = QtGui.QLabel(self.grpMap)
        self.label3.setIndent(20)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout_2.addWidget(self.label3, 1, 2, 1, 1)
        self.txtGeneralMapWidth = QtGui.QLineEdit(self.grpMap)
        self.txtGeneralMapWidth.setText(_fromUtf8("600"))
        self.txtGeneralMapWidth.setObjectName(_fromUtf8("txtGeneralMapWidth"))
        self.gridLayout_2.addWidget(self.txtGeneralMapWidth, 1, 1, 1, 1)
        self.cmbGeneralMapImageType = QtGui.QComboBox(self.grpMap)
        self.cmbGeneralMapImageType.setObjectName(_fromUtf8("cmbGeneralMapImageType"))
        self.gridLayout_2.addWidget(self.cmbGeneralMapImageType, 0, 5, 1, 1)
        self.label1 = QtGui.QLabel(self.grpMap)
        self.label1.setToolTip(_fromUtf8(""))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout_2.addWidget(self.label1, 0, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.grpMap)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 4, 0, 1, 1)
        self.txtMetadataMapDebugLevel = QtGui.QLineEdit(self.grpMap)
        self.txtMetadataMapDebugLevel.setObjectName(_fromUtf8("txtMetadataMapDebugLevel"))
        self.gridLayout_2.addWidget(self.txtMetadataMapDebugLevel, 4, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.grpMap)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 2, 2, 1, 1)
        self.txtMetadataMapMsErrorFilePath = QtGui.QLineEdit(self.grpMap)
        self.txtMetadataMapMsErrorFilePath.setObjectName(_fromUtf8("txtMetadataMapMsErrorFilePath"))
        self.gridLayout_2.addWidget(self.txtMetadataMapMsErrorFilePath, 2, 3, 1, 1)
        self.gridLayout_3.addWidget(self.grpMap, 1, 0, 1, 3)
        self.txtMapFilePath = QtGui.QLineEdit(self.tabGeneral)
        self.txtMapFilePath.setText(_fromUtf8(""))
        self.txtMapFilePath.setObjectName(_fromUtf8("txtMapFilePath"))
        self.gridLayout_3.addWidget(self.txtMapFilePath, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tabGeneral)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.btnChooseFile = QtGui.QToolButton(self.tabGeneral)
        self.btnChooseFile.setObjectName(_fromUtf8("btnChooseFile"))
        self.gridLayout_3.addWidget(self.btnChooseFile, 0, 2, 1, 1)
        self.tabWiget.addTab(self.tabGeneral, _fromUtf8(""))
        self.tabMatadata = QtGui.QWidget()
        self.tabMatadata.setObjectName(_fromUtf8("tabMatadata"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tabMatadata)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 791, 581))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tabMetadataOws = QtGui.QWidget()
        self.tabMetadataOws.setObjectName(_fromUtf8("tabMetadataOws"))
        self.scrollArea = QtGui.QScrollArea(self.tabMetadataOws)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 761, 551))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.frame = QtGui.QFrame()
        self.frame.setGeometry(QtCore.QRect(0, 0, 759, 549))
        self.frame.setMinimumSize(QtCore.QSize(500, 400))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBoxMetadataOws = QtGui.QGroupBox(self.frame)
        self.groupBoxMetadataOws.setGeometry(QtCore.QRect(0, 60, 741, 391))
        self.groupBoxMetadataOws.setObjectName(_fromUtf8("groupBoxMetadataOws"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBoxMetadataOws)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_42 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_9.addWidget(self.label_42, 2, 0, 1, 1)
        self.txtMetadataOwsOwsTitle = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsOwsTitle.setText(_fromUtf8(""))
        self.txtMetadataOwsOwsTitle.setObjectName(_fromUtf8("txtMetadataOwsOwsTitle"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsOwsTitle, 3, 1, 1, 1)
        self.txtMetadataOwsWebOwsUpdatesequence = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsWebOwsUpdatesequence.setObjectName(_fromUtf8("txtMetadataOwsWebOwsUpdatesequence"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsWebOwsUpdatesequence, 7, 3, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_9.addWidget(self.label_48, 7, 2, 1, 1)
        self.txtMetadataOwsWebOwsSldEnabled = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsWebOwsSldEnabled.setObjectName(_fromUtf8("txtMetadataOwsWebOwsSldEnabled"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsWebOwsSldEnabled, 8, 3, 1, 1)
        self.txtMetadataOwsOwsEnableRequest = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsOwsEnableRequest.setText(_fromUtf8(""))
        self.txtMetadataOwsOwsEnableRequest.setObjectName(_fromUtf8("txtMetadataOwsOwsEnableRequest"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsOwsEnableRequest, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_9.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_9.addWidget(self.label_23, 6, 2, 1, 1)
        self.txtMetadataOwsWebOwsDeniedIpList = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsWebOwsDeniedIpList.setObjectName(_fromUtf8("txtMetadataOwsWebOwsDeniedIpList"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsWebOwsDeniedIpList, 6, 3, 1, 1)
        self.txtMetadataOwsWebOwsSchemasLocation = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsWebOwsSchemasLocation.setObjectName(_fromUtf8("txtMetadataOwsWebOwsSchemasLocation"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsWebOwsSchemasLocation, 7, 1, 1, 1)
        self.txtMetadataOwsWebOwsAllowedIpList = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsWebOwsAllowedIpList.setObjectName(_fromUtf8("txtMetadataOwsWebOwsAllowedIpList"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsWebOwsAllowedIpList, 6, 1, 1, 1)
        self.txtMetadataOwsOwsOnlineResource = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsOwsOnlineResource.setText(_fromUtf8(""))
        self.txtMetadataOwsOwsOnlineResource.setObjectName(_fromUtf8("txtMetadataOwsOwsOnlineResource"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsOwsOnlineResource, 4, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_9.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 1, 0, 1, 1)
        self.txtMetadataOwsOwsSrs = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsOwsSrs.setObjectName(_fromUtf8("txtMetadataOwsOwsSrs"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsOwsSrs, 3, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_9.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_9.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_69 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_9.addWidget(self.label_69, 8, 2, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_9.addWidget(self.label_49, 7, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_70 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_9.addWidget(self.label_70, 8, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBoxMetadataOws)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 3, 2, 1, 1)
        self.txtMetadataOwsWebOwsHttpMaxAge = QtGui.QLineEdit(self.groupBoxMetadataOws)
        self.txtMetadataOwsWebOwsHttpMaxAge.setObjectName(_fromUtf8("txtMetadataOwsWebOwsHttpMaxAge"))
        self.gridLayout_9.addWidget(self.txtMetadataOwsWebOwsHttpMaxAge, 8, 1, 1, 1)
        self.checkBoxOws = QtGui.QCheckBox(self.frame)
        self.checkBoxOws.setGeometry(QtCore.QRect(10, 20, 152, 20))
        self.checkBoxOws.setObjectName(_fromUtf8("checkBoxOws"))
        self.scrollArea.setWidget(self.frame)
        self.tabWidget_2.addTab(self.tabMetadataOws, _fromUtf8(""))
        self.tabMetadataWms = QtGui.QWidget()
        self.tabMetadataWms.setObjectName(_fromUtf8("tabMetadataWms"))
        self.scrollArea1 = QtGui.QScrollArea(self.tabMetadataWms)
        self.scrollArea1.setGeometry(QtCore.QRect(0, 0, 761, 551))
        self.scrollArea1.setWidgetResizable(True)
        self.scrollArea1.setObjectName(_fromUtf8("scrollArea1"))
        self.frame1 = QtGui.QFrame()
        self.frame1.setGeometry(QtCore.QRect(0, -151, 744, 700))
        self.frame1.setMinimumSize(QtCore.QSize(500, 700))
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.groupBoxMetadataWms = QtGui.QGroupBox(self.frame1)
        self.groupBoxMetadataWms.setGeometry(QtCore.QRect(0, 60, 741, 611))
        self.groupBoxMetadataWms.setObjectName(_fromUtf8("groupBoxMetadataWms"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBoxMetadataWms)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.txtMetadataWmsWebWmsFeatureInfoMimeType = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsFeatureInfoMimeType.setObjectName(_fromUtf8("txtMetadataWmsWebWmsFeatureInfoMimeType"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsFeatureInfoMimeType, 7, 3, 1, 1)
        self.label_64 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_10.addWidget(self.label_64, 13, 2, 1, 1)
        self.label_66 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_10.addWidget(self.label_66, 12, 2, 1, 1)
        self.label_58 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_10.addWidget(self.label_58, 3, 0, 1, 1)
        self.txtMetadataWmsWebWmsLayerlimit = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsLayerlimit.setObjectName(_fromUtf8("txtMetadataWmsWebWmsLayerlimit"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsLayerlimit, 12, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_10.addWidget(self.label_19, 11, 0, 1, 1)
        self.txtMetadataWmsWebWmsSrs = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsSrs.setObjectName(_fromUtf8("txtMetadataWmsWebWmsSrs"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsSrs, 3, 3, 1, 1)
        self.txtMetadataWmsWebWmsAttrbutionOnlineresource = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsAttrbutionOnlineresource.setObjectName(_fromUtf8("txtMetadataWmsWebWmsAttrbutionOnlineresource"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsAttrbutionOnlineresource, 6, 1, 1, 1)
        self.label_63 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_10.addWidget(self.label_63, 18, 0, 1, 1)
        self.label_60 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_10.addWidget(self.label_60, 14, 0, 1, 1)
        self.txtMetadataWmsWebWmsRemoteSldMaxBytes = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsRemoteSldMaxBytes.setObjectName(_fromUtf8("txtMetadataWmsWebWmsRemoteSldMaxBytes"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsRemoteSldMaxBytes, 13, 1, 1, 1)
        self.txtMetadataWmsWebWmsEnableRequest = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsEnableRequest.setText(_fromUtf8(""))
        self.txtMetadataWmsWebWmsEnableRequest.setObjectName(_fromUtf8("txtMetadataWmsWebWmsEnableRequest"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsEnableRequest, 1, 1, 1, 1)
        self.txtMetadataWmsWebWmsTitle = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsTitle.setText(_fromUtf8(""))
        self.txtMetadataWmsWebWmsTitle.setObjectName(_fromUtf8("txtMetadataWmsWebWmsTitle"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsTitle, 1, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_10.addWidget(self.label_21, 2, 0, 1, 1)
        self.txtMetadataWmsWebWmsTimeformat = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsTimeformat.setObjectName(_fromUtf8("txtMetadataWmsWebWmsTimeformat"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsTimeformat, 18, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_10.addWidget(self.label_46, 12, 0, 1, 1)
        self.txtMetadataWmsWebWmsGetlegendgraphicFormailist = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsGetlegendgraphicFormailist.setObjectName(_fromUtf8("txtMetadataWmsWebWmsGetlegendgraphicFormailist"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsGetlegendgraphicFormailist, 10, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_10.addWidget(self.label_16, 9, 0, 1, 1)
        self.txtMetadataWmsWebWmsResy = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsResy.setObjectName(_fromUtf8("txtMetadataWmsWebWmsResy"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsResy, 14, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_10.addWidget(self.label_14, 8, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_10.addWidget(self.label_18, 10, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_10.addWidget(self.label_17, 8, 2, 1, 1)
        self.label_59 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_10.addWidget(self.label_59, 13, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_10.addWidget(self.label_11, 6, 2, 1, 1)
        self.txtMetadataWmsWebWmsFees = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsFees.setObjectName(_fromUtf8("txtMetadataWmsWebWmsFees"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsFees, 9, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_10.addWidget(self.label_26, 10, 2, 1, 1)
        self.txtMetadataWmsWebWmsLanguages = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsLanguages.setObjectName(_fromUtf8("txtMetadataWmsWebWmsLanguages"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsLanguages, 11, 3, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_10.addWidget(self.label_67, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_10.addWidget(self.label_10, 6, 0, 1, 1)
        self.txtMetadataWmsWebWmsRootlayerKeywordlist = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsRootlayerKeywordlist.setObjectName(_fromUtf8("txtMetadataWmsWebWmsRootlayerKeywordlist"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsRootlayerKeywordlist, 12, 3, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_10.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_10.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_68 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_10.addWidget(self.label_68, 1, 2, 1, 1)
        self.label_61 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_10.addWidget(self.label_61, 16, 0, 1, 1)
        self.txtMetadataWmsWebWmsKeywordlist = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsKeywordlist.setObjectName(_fromUtf8("txtMetadataWmsWebWmsKeywordlist"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsKeywordlist, 11, 1, 1, 1)
        self.txtMetadataWmsWebWmsEncoding = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsEncoding.setObjectName(_fromUtf8("txtMetadataWmsWebWmsEncoding"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsEncoding, 8, 1, 1, 1)
        self.label_65 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_10.addWidget(self.label_65, 14, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_10.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_10.addWidget(self.label_13, 1, 0, 1, 1)
        self.txtMetadataWmsWebWmsOnlineresource = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsOnlineresource.setText(_fromUtf8(""))
        self.txtMetadataWmsWebWmsOnlineresource.setObjectName(_fromUtf8("txtMetadataWmsWebWmsOnlineresource"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsOnlineresource, 3, 1, 1, 1)
        self.txtMetadataWmsWebWmsRootlayerAbstract = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsRootlayerAbstract.setObjectName(_fromUtf8("txtMetadataWmsWebWmsRootlayerAbstract"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsRootlayerAbstract, 16, 1, 1, 1)
        self.txtMetadataWmsWebWmsBboxExtended = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsBboxExtended.setObjectName(_fromUtf8("txtMetadataWmsWebWmsBboxExtended"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsBboxExtended, 7, 1, 1, 1)
        self.txtMetadataWmsWebWmsResx = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsResx.setObjectName(_fromUtf8("txtMetadataWmsWebWmsResx"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsResx, 14, 1, 1, 1)
        self.txtMetadataWmsWebWmsAttributionTitle = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsAttributionTitle.setObjectName(_fromUtf8("txtMetadataWmsWebWmsAttributionTitle"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsAttributionTitle, 6, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_10.addWidget(self.label_25, 9, 2, 1, 1)
        self.txtMetadataWmsWebWmsGetcapabilitiesVersion = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsGetcapabilitiesVersion.setObjectName(_fromUtf8("txtMetadataWmsWebWmsGetcapabilitiesVersion"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsGetcapabilitiesVersion, 8, 3, 1, 1)
        self.txtMetadataWmsWebWmsServiceOnlineResource = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsServiceOnlineResource.setObjectName(_fromUtf8("txtMetadataWmsWebWmsServiceOnlineResource"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsServiceOnlineResource, 13, 3, 1, 1)
        self.txtMetadataWmsWebWmsGetmapFormallist = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsGetmapFormallist.setObjectName(_fromUtf8("txtMetadataWmsWebWmsGetmapFormallist"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsGetmapFormallist, 9, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_10.addWidget(self.label_15, 7, 2, 1, 1)
        self.txtMetadataWmsWebWmsRootlayerTitle = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsRootlayerTitle.setObjectName(_fromUtf8("txtMetadataWmsWebWmsRootlayerTitle"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsRootlayerTitle, 16, 3, 1, 1)
        self.txtMetadataWmsWebWmsKeywordlistVocabulary = QtGui.QLineEdit(self.groupBoxMetadataWms)
        self.txtMetadataWmsWebWmsKeywordlistVocabulary.setObjectName(_fromUtf8("txtMetadataWmsWebWmsKeywordlistVocabulary"))
        self.gridLayout_10.addWidget(self.txtMetadataWmsWebWmsKeywordlistVocabulary, 10, 3, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_10.addWidget(self.label_47, 11, 2, 1, 1)
        self.label_62 = QtGui.QLabel(self.groupBoxMetadataWms)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_10.addWidget(self.label_62, 16, 2, 1, 1)
        self.checkBoxWms = QtGui.QCheckBox(self.frame1)
        self.checkBoxWms.setGeometry(QtCore.QRect(10, 20, 219, 20))
        self.checkBoxWms.setObjectName(_fromUtf8("checkBoxWms"))
        self.scrollArea1.setWidget(self.frame1)
        self.tabWidget_2.addTab(self.tabMetadataWms, _fromUtf8(""))
        self.tabMetadataWfs = QtGui.QWidget()
        self.tabMetadataWfs.setObjectName(_fromUtf8("tabMetadataWfs"))
        self.scrollArea2 = QtGui.QScrollArea(self.tabMetadataWfs)
        self.scrollArea2.setGeometry(QtCore.QRect(0, 0, 761, 551))
        self.scrollArea2.setWidgetResizable(True)
        self.scrollArea2.setObjectName(_fromUtf8("scrollArea2"))
        self.frame2 = QtGui.QFrame()
        self.frame2.setGeometry(QtCore.QRect(0, 0, 759, 549))
        self.frame2.setMinimumSize(QtCore.QSize(500, 500))
        self.frame2.setObjectName(_fromUtf8("frame2"))
        self.groupBoxMetadataWfs = QtGui.QGroupBox(self.frame2)
        self.groupBoxMetadataWfs.setEnabled(True)
        self.groupBoxMetadataWfs.setGeometry(QtCore.QRect(0, 60, 741, 451))
        self.groupBoxMetadataWfs.setObjectName(_fromUtf8("groupBoxMetadataWfs"))
        self.gridLayout_101 = QtGui.QGridLayout(self.groupBoxMetadataWfs)
        self.gridLayout_101.setObjectName(_fromUtf8("gridLayout_101"))
        self.label_151 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_151.setObjectName(_fromUtf8("label_151"))
        self.gridLayout_101.addWidget(self.label_151, 7, 2, 1, 1)
        self.label_251 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_251.setObjectName(_fromUtf8("label_251"))
        self.gridLayout_101.addWidget(self.label_251, 9, 2, 1, 1)
        self.txtMetadataWfsWebWfsEnableRequest = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsEnableRequest.setText(_fromUtf8(""))
        self.txtMetadataWfsWebWfsEnableRequest.setObjectName(_fromUtf8("txtMetadataWfsWebWfsEnableRequest"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsEnableRequest, 1, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_101.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_101.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_471 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_471.setObjectName(_fromUtf8("label_471"))
        self.gridLayout_101.addWidget(self.label_471, 3, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_101.addWidget(self.label_45, 10, 2, 1, 1)
        self.txtMetadataWfsWebWfsTitle = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsTitle.setText(_fromUtf8(""))
        self.txtMetadataWfsWebWfsTitle.setObjectName(_fromUtf8("txtMetadataWfsWebWfsTitle"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsTitle, 1, 3, 1, 1)
        self.label_191 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_191.setObjectName(_fromUtf8("label_191"))
        self.gridLayout_101.addWidget(self.label_191, 11, 0, 1, 1)
        self.txtMetadataWfsWebWfsServiceOnlineresource = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsServiceOnlineresource.setObjectName(_fromUtf8("txtMetadataWfsWebWfsServiceOnlineresource"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsServiceOnlineresource, 10, 3, 1, 1)
        self.txtMetadataWfsWebWfsEncoding = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsEncoding.setObjectName(_fromUtf8("txtMetadataWfsWebWfsEncoding"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsEncoding, 7, 1, 1, 1)
        self.txtMetadataWfsWebWfsAccessconstraints = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsAccessconstraints.setObjectName(_fromUtf8("txtMetadataWfsWebWfsAccessconstraints"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsAccessconstraints, 6, 3, 1, 1)
        self.txtMetadataWfsWebWfsNamespacePrefix = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsNamespacePrefix.setObjectName(_fromUtf8("txtMetadataWfsWebWfsNamespacePrefix"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsNamespacePrefix, 9, 3, 1, 1)
        self.label_111 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.gridLayout_101.addWidget(self.label_111, 6, 2, 1, 1)
        self.txtMetadataWfsWebWfsGetcapabilitiesVersion = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsGetcapabilitiesVersion.setObjectName(_fromUtf8("txtMetadataWfsWebWfsGetcapabilitiesVersion"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsGetcapabilitiesVersion, 9, 1, 1, 1)
        self.txtMetadataWfsWebWfsFees = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsFees.setObjectName(_fromUtf8("txtMetadataWfsWebWfsFees"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsFees, 8, 1, 1, 1)
        self.label_141 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_141.setObjectName(_fromUtf8("label_141"))
        self.gridLayout_101.addWidget(self.label_141, 8, 0, 1, 1)
        self.label_161 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_161.setObjectName(_fromUtf8("label_161"))
        self.gridLayout_101.addWidget(self.label_161, 9, 0, 1, 1)
        self.txtMetadataWfsWebWfsKeywordlist = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsKeywordlist.setObjectName(_fromUtf8("txtMetadataWfsWebWfsKeywordlist"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsKeywordlist, 8, 3, 1, 1)
        self.label_101 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout_101.addWidget(self.label_101, 6, 0, 1, 1)
        self.txtMetadataWfsWebWfsNamespaceUri = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsNamespaceUri.setObjectName(_fromUtf8("txtMetadataWfsWebWfsNamespaceUri"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsNamespaceUri, 11, 1, 1, 1)
        self.label_181 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_181.setObjectName(_fromUtf8("label_181"))
        self.gridLayout_101.addWidget(self.label_181, 10, 0, 1, 1)
        self.txtMetadataWfsWebWfsAbstract = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsAbstract.setObjectName(_fromUtf8("txtMetadataWfsWebWfsAbstract"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsAbstract, 6, 1, 1, 1)
        self.label_121 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.gridLayout_101.addWidget(self.label_121, 7, 0, 1, 1)
        self.txtMetadataWfsWebWfsMaxfeatures = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsMaxfeatures.setObjectName(_fromUtf8("txtMetadataWfsWebWfsMaxfeatures"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsMaxfeatures, 10, 1, 1, 1)
        self.txtMetadataWfsWebWfsOnlineresource = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsOnlineresource.setText(_fromUtf8(""))
        self.txtMetadataWfsWebWfsOnlineresource.setObjectName(_fromUtf8("txtMetadataWfsWebWfsOnlineresource"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsOnlineresource, 3, 1, 1, 1)
        self.label_261 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_261.setObjectName(_fromUtf8("label_261"))
        self.gridLayout_101.addWidget(self.label_261, 3, 0, 1, 1)
        self.txtMetadataWfsWebWfsSrs = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsSrs.setObjectName(_fromUtf8("txtMetadataWfsWebWfsSrs"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsSrs, 3, 3, 1, 1)
        self.label_131 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_131.setObjectName(_fromUtf8("label_131"))
        self.gridLayout_101.addWidget(self.label_131, 1, 0, 1, 1)
        self.label_171 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_171.setObjectName(_fromUtf8("label_171"))
        self.gridLayout_101.addWidget(self.label_171, 8, 2, 1, 1)
        self.label_461 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_461.setObjectName(_fromUtf8("label_461"))
        self.gridLayout_101.addWidget(self.label_461, 1, 2, 1, 1)
        self.txtMetadataWfsWebWfsFeatureCollection = QtGui.QLineEdit(self.groupBoxMetadataWfs)
        self.txtMetadataWfsWebWfsFeatureCollection.setObjectName(_fromUtf8("txtMetadataWfsWebWfsFeatureCollection"))
        self.gridLayout_101.addWidget(self.txtMetadataWfsWebWfsFeatureCollection, 7, 3, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBoxMetadataWfs)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_101.addWidget(self.label_33, 4, 0, 1, 1)
        self.checkBoxWfs = QtGui.QCheckBox(self.frame2)
        self.checkBoxWfs.setGeometry(QtCore.QRect(10, 20, 180, 20))
        self.checkBoxWfs.setObjectName(_fromUtf8("checkBoxWfs"))
        self.scrollArea2.setWidget(self.frame2)
        self.tabWidget_2.addTab(self.tabMetadataWfs, _fromUtf8(""))
        self.tabMetadataWcs = QtGui.QWidget()
        self.tabMetadataWcs.setObjectName(_fromUtf8("tabMetadataWcs"))
        self.scrollArea3 = QtGui.QScrollArea(self.tabMetadataWcs)
        self.scrollArea3.setGeometry(QtCore.QRect(0, 0, 761, 551))
        self.scrollArea3.setWidgetResizable(True)
        self.scrollArea3.setObjectName(_fromUtf8("scrollArea3"))
        self.frame3 = QtGui.QFrame()
        self.frame3.setGeometry(QtCore.QRect(0, 0, 759, 549))
        self.frame3.setMinimumSize(QtCore.QSize(500, 400))
        self.frame3.setObjectName(_fromUtf8("frame3"))
        self.groupBoxMetadataWcs = QtGui.QGroupBox(self.frame3)
        self.groupBoxMetadataWcs.setGeometry(QtCore.QRect(0, 60, 741, 331))
        self.groupBoxMetadataWcs.setObjectName(_fromUtf8("groupBoxMetadataWcs"))
        self.gridLayout_102 = QtGui.QGridLayout(self.groupBoxMetadataWcs)
        self.gridLayout_102.setObjectName(_fromUtf8("gridLayout_102"))
        self.label_132 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_132.setObjectName(_fromUtf8("label_132"))
        self.gridLayout_102.addWidget(self.label_132, 1, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_102.addWidget(self.label_36, 0, 0, 1, 1)
        self.txtMetadataWcsWebWcsKeywords = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsKeywords.setObjectName(_fromUtf8("txtMetadataWcsWebWcsKeywords"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsKeywords, 4, 3, 1, 1)
        self.label_252 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_252.setObjectName(_fromUtf8("label_252"))
        self.gridLayout_102.addWidget(self.label_252, 7, 2, 1, 1)
        self.txtMetadataWcsWebWcsMetadatalinkType = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsMetadatalinkType.setObjectName(_fromUtf8("txtMetadataWcsWebWcsMetadatalinkType"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsMetadatalinkType, 7, 3, 1, 1)
        self.txtMetadataWcsWebWcsAccessconstraints = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsAccessconstraints.setObjectName(_fromUtf8("txtMetadataWcsWebWcsAccessconstraints"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsAccessconstraints, 3, 3, 1, 1)
        self.txtMetadataWcsWebWcsMetadatalinkFormat = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsMetadatalinkFormat.setObjectName(_fromUtf8("txtMetadataWcsWebWcsMetadatalinkFormat"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsMetadatalinkFormat, 5, 3, 1, 1)
        self.label_192 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_192.setObjectName(_fromUtf8("label_192"))
        self.gridLayout_102.addWidget(self.label_192, 8, 0, 1, 1)
        self.txtMetadataWcsWebWcsMetadatalinkHref = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsMetadatalinkHref.setObjectName(_fromUtf8("txtMetadataWcsWebWcsMetadatalinkHref"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsMetadatalinkHref, 7, 1, 1, 1)
        self.txtMetadataWcsWebWcsAbstract = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsAbstract.setObjectName(_fromUtf8("txtMetadataWcsWebWcsAbstract"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsAbstract, 3, 1, 1, 1)
        self.label_112 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.gridLayout_102.addWidget(self.label_112, 3, 2, 1, 1)
        self.txtMetadataWcsWebWcsServiceOnlineresource = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsServiceOnlineresource.setObjectName(_fromUtf8("txtMetadataWcsWebWcsServiceOnlineresource"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsServiceOnlineresource, 8, 3, 1, 1)
        self.txtMetadataWcsWebWcsName = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsName.setObjectName(_fromUtf8("txtMetadataWcsWebWcsName"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsName, 8, 1, 1, 1)
        self.label_142 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_142.setObjectName(_fromUtf8("label_142"))
        self.gridLayout_102.addWidget(self.label_142, 5, 0, 1, 1)
        self.txtMetadataWcsWebWcsFees = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsFees.setObjectName(_fromUtf8("txtMetadataWcsWebWcsFees"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsFees, 5, 1, 1, 1)
        self.label_102 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout_102.addWidget(self.label_102, 3, 0, 1, 1)
        self.txtMetadataWcsWebWcsDescription = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsDescription.setObjectName(_fromUtf8("txtMetadataWcsWebWcsDescription"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsDescription, 4, 1, 1, 1)
        self.label_122 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.gridLayout_102.addWidget(self.label_122, 4, 0, 1, 1)
        self.txtMetadataWcsWebWcsLabel = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsLabel.setText(_fromUtf8(""))
        self.txtMetadataWcsWebWcsLabel.setObjectName(_fromUtf8("txtMetadataWcsWebWcsLabel"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsLabel, 1, 3, 1, 1)
        self.label_262 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_262.setObjectName(_fromUtf8("label_262"))
        self.gridLayout_102.addWidget(self.label_262, 8, 2, 1, 1)
        self.label_182 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_182.setObjectName(_fromUtf8("label_182"))
        self.gridLayout_102.addWidget(self.label_182, 7, 0, 1, 1)
        self.txtMetadataWcsWebWcsEnableRequest = QtGui.QLineEdit(self.groupBoxMetadataWcs)
        self.txtMetadataWcsWebWcsEnableRequest.setText(_fromUtf8(""))
        self.txtMetadataWcsWebWcsEnableRequest.setObjectName(_fromUtf8("txtMetadataWcsWebWcsEnableRequest"))
        self.gridLayout_102.addWidget(self.txtMetadataWcsWebWcsEnableRequest, 1, 1, 1, 1)
        self.label_162 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_162.setObjectName(_fromUtf8("label_162"))
        self.gridLayout_102.addWidget(self.label_162, 1, 2, 1, 1)
        self.label_172 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_172.setObjectName(_fromUtf8("label_172"))
        self.gridLayout_102.addWidget(self.label_172, 5, 2, 1, 1)
        self.label_152 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_152.setObjectName(_fromUtf8("label_152"))
        self.gridLayout_102.addWidget(self.label_152, 4, 2, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBoxMetadataWcs)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_102.addWidget(self.label_37, 2, 0, 1, 1)
        self.checkBoxWcs = QtGui.QCheckBox(self.frame3)
        self.checkBoxWcs.setGeometry(QtCore.QRect(10, 20, 152, 20))
        self.checkBoxWcs.setObjectName(_fromUtf8("checkBoxWcs"))
        self.scrollArea3.setWidget(self.frame3)
        self.tabWidget_2.addTab(self.tabMetadataWcs, _fromUtf8(""))
        self.tabWiget.addTab(self.tabMatadata, _fromUtf8(""))
        self.tabTemplate = QtGui.QWidget()
        self.tabTemplate.setObjectName(_fromUtf8("tabTemplate"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabTemplate)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.checkTmplFromFile = QtGui.QRadioButton(self.tabTemplate)
        self.checkTmplFromFile.setChecked(True)
        self.checkTmplFromFile.setObjectName(_fromUtf8("checkTmplFromFile"))
        self.gridLayout_7.addWidget(self.checkTmplFromFile, 0, 0, 1, 3)
        self.txtTemplatePath = QtGui.QLineEdit(self.tabTemplate)
        self.txtTemplatePath.setText(_fromUtf8("dummy"))
        self.txtTemplatePath.setObjectName(_fromUtf8("txtTemplatePath"))
        self.gridLayout_7.addWidget(self.txtTemplatePath, 0, 3, 1, 1)
        self.btnChooseTemplate = QtGui.QToolButton(self.tabTemplate)
        self.btnChooseTemplate.setObjectName(_fromUtf8("btnChooseTemplate"))
        self.gridLayout_7.addWidget(self.btnChooseTemplate, 0, 4, 1, 1)
        self.checkGenerateTmpl = QtGui.QRadioButton(self.tabTemplate)
        self.checkGenerateTmpl.setObjectName(_fromUtf8("checkGenerateTmpl"))
        self.gridLayout_7.addWidget(self.checkGenerateTmpl, 1, 0, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 2, 0, 1, 1)
        self.templateTable = QtGui.QTableView(self.tabTemplate)
        self.templateTable.setEnabled(False)
        self.templateTable.setObjectName(_fromUtf8("templateTable"))
        self.gridLayout_7.addWidget(self.templateTable, 2, 1, 1, 4)
        self.label_2 = QtGui.QLabel(self.tabTemplate)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 3, 0, 1, 2)
        self.txtTmplHeaderPath = QtGui.QLineEdit(self.tabTemplate)
        self.txtTmplHeaderPath.setText(_fromUtf8(""))
        self.txtTmplHeaderPath.setObjectName(_fromUtf8("txtTmplHeaderPath"))
        self.gridLayout_7.addWidget(self.txtTmplHeaderPath, 3, 2, 1, 2)
        self.btnChooseTmplHeader = QtGui.QToolButton(self.tabTemplate)
        self.btnChooseTmplHeader.setObjectName(_fromUtf8("btnChooseTmplHeader"))
        self.gridLayout_7.addWidget(self.btnChooseTmplHeader, 3, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabTemplate)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 4, 0, 1, 2)
        self.txtTmplFooterPath = QtGui.QLineEdit(self.tabTemplate)
        self.txtTmplFooterPath.setText(_fromUtf8(""))
        self.txtTmplFooterPath.setObjectName(_fromUtf8("txtTmplFooterPath"))
        self.gridLayout_7.addWidget(self.txtTmplFooterPath, 4, 2, 1, 2)
        self.btnChooseTmplFooter = QtGui.QToolButton(self.tabTemplate)
        self.btnChooseTmplFooter.setObjectName(_fromUtf8("btnChooseTmplFooter"))
        self.gridLayout_7.addWidget(self.btnChooseTmplFooter, 4, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 5, 0, 1, 5)
        self.tabWiget.addTab(self.tabTemplate, _fromUtf8(""))
        self.tabAdvanced = QtGui.QWidget()
        self.tabAdvanced.setObjectName(_fromUtf8("tabAdvanced"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabAdvanced)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.grpOptions = QtGui.QGroupBox(self.tabAdvanced)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpOptions.sizePolicy().hasHeightForWidth())
        self.grpOptions.setSizePolicy(sizePolicy)
        self.grpOptions.setObjectName(_fromUtf8("grpOptions"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grpOptions)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.checkBoxForce = QtGui.QCheckBox(self.grpOptions)
        self.checkBoxForce.setObjectName(_fromUtf8("checkBoxForce"))
        self.gridLayout_5.addWidget(self.checkBoxForce, 0, 0, 1, 1)
        self.checkBoxPartials = QtGui.QCheckBox(self.grpOptions)
        self.checkBoxPartials.setObjectName(_fromUtf8("checkBoxPartials"))
        self.gridLayout_5.addWidget(self.checkBoxPartials, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.grpOptions, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 2, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tabAdvanced)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label6_3 = QtGui.QLabel(self.groupBox_3)
        self.label6_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label6_3.setObjectName(_fromUtf8("label6_3"))
        self.gridLayout_6.addWidget(self.label6_3, 0, 0, 1, 1)
        self.txtMapFontsetPath = QtGui.QLineEdit(self.groupBox_3)
        self.txtMapFontsetPath.setText(_fromUtf8(""))
        self.txtMapFontsetPath.setObjectName(_fromUtf8("txtMapFontsetPath"))
        self.gridLayout_6.addWidget(self.txtMapFontsetPath, 0, 1, 1, 1)
        self.checkCreateFontFile = QtGui.QCheckBox(self.groupBox_3)
        self.checkCreateFontFile.setObjectName(_fromUtf8("checkCreateFontFile"))
        self.gridLayout_6.addWidget(self.checkCreateFontFile, 1, 0, 1, 2)
        self.gridLayout_8.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWiget.addTab(self.tabAdvanced, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWiget, 1, 0, 1, 1)
        self.label6.setBuddy(self.txtGeneralWebServerUrl)
        self.label6_5.setBuddy(self.txtGeneralWebServerUrl)
        self.label6_4.setBuddy(self.txtGeneralWebServerUrl)
        self.label6_7.setBuddy(self.txtGeneralWebServerUrl)
        self.label6_6.setBuddy(self.txtGeneralWebServerUrl)
        self.label5.setBuddy(self.cmbGeneralMapImageType)
        self.label2.setBuddy(self.txtGeneralMapWidth)
        self.label4.setBuddy(self.cmbGeneralMapUnits)
        self.label3.setBuddy(self.txtGeneralMapHeight)
        self.label1.setBuddy(self.txtGeneralMapName)
        self.label.setBuddy(self.txtMapFilePath)
        self.label6_3.setBuddy(self.txtGeneralWebServerUrl)

        self.retranslateUi(MapfileExportDlg)
        self.tabWiget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MapfileExportDlg.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MapfileExportDlg.accept)
        QtCore.QObject.connect(self.checkGenerateTmpl, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.templateTable.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MapfileExportDlg)
        MapfileExportDlg.setTabOrder(self.txtMapFilePath, self.txtGeneralMapName)
        MapfileExportDlg.setTabOrder(self.txtGeneralMapName, self.cmbGeneralMapImageType)
        MapfileExportDlg.setTabOrder(self.cmbGeneralMapImageType, self.txtGeneralMapWidth)
        MapfileExportDlg.setTabOrder(self.txtGeneralMapWidth, self.txtGeneralMapHeight)
        MapfileExportDlg.setTabOrder(self.txtGeneralMapHeight, self.cmbGeneralMapUnits)
        MapfileExportDlg.setTabOrder(self.cmbGeneralMapUnits, self.txtGeneralMapProjLibFolder)
        MapfileExportDlg.setTabOrder(self.txtGeneralMapProjLibFolder, self.txtMetadataMapMsErrorFilePath)
        MapfileExportDlg.setTabOrder(self.txtMetadataMapMsErrorFilePath, self.txtMetadataMapDebugLevel)
        MapfileExportDlg.setTabOrder(self.txtMetadataMapDebugLevel, self.txtGeneralWebServerUrl)
        MapfileExportDlg.setTabOrder(self.txtGeneralWebServerUrl, self.txtGeneralWebImagePath)
        MapfileExportDlg.setTabOrder(self.txtGeneralWebImagePath, self.txtGeneralWebImageUrl)
        MapfileExportDlg.setTabOrder(self.txtGeneralWebImageUrl, self.txtGeneralWebTempPath)
        MapfileExportDlg.setTabOrder(self.txtGeneralWebTempPath, self.txtGeneralExternalGraphicRegexp)
        MapfileExportDlg.setTabOrder(self.txtGeneralExternalGraphicRegexp, self.checkBoxOws)
        MapfileExportDlg.setTabOrder(self.checkBoxOws, self.txtMetadataOwsOwsEnableRequest)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsOwsEnableRequest, self.txtMetadataOwsOwsTitle)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsOwsTitle, self.txtMetadataOwsOwsSrs)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsOwsSrs, self.txtMetadataOwsOwsOnlineResource)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsOwsOnlineResource, self.txtMetadataOwsWebOwsAllowedIpList)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsWebOwsAllowedIpList, self.txtMetadataOwsWebOwsDeniedIpList)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsWebOwsDeniedIpList, self.txtMetadataOwsWebOwsSchemasLocation)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsWebOwsSchemasLocation, self.txtMetadataOwsWebOwsUpdatesequence)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsWebOwsUpdatesequence, self.txtMetadataOwsWebOwsHttpMaxAge)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsWebOwsHttpMaxAge, self.txtMetadataOwsWebOwsSldEnabled)
        MapfileExportDlg.setTabOrder(self.txtMetadataOwsWebOwsSldEnabled, self.checkBoxWms)
        MapfileExportDlg.setTabOrder(self.checkBoxWms, self.txtMetadataWmsWebWmsEnableRequest)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsEnableRequest, self.txtMetadataWmsWebWmsTitle)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsTitle, self.txtMetadataWmsWebWmsOnlineresource)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsOnlineresource, self.txtMetadataWmsWebWmsSrs)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsSrs, self.txtMetadataWmsWebWmsAttrbutionOnlineresource)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsAttrbutionOnlineresource, self.txtMetadataWmsWebWmsAttributionTitle)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsAttributionTitle, self.txtMetadataWmsWebWmsBboxExtended)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsBboxExtended, self.txtMetadataWmsWebWmsFeatureInfoMimeType)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsFeatureInfoMimeType, self.txtMetadataWmsWebWmsEncoding)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsEncoding, self.txtMetadataWmsWebWmsGetcapabilitiesVersion)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsGetcapabilitiesVersion, self.txtMetadataWmsWebWmsFees)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsFees, self.txtMetadataWmsWebWmsGetmapFormallist)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsGetmapFormallist, self.txtMetadataWmsWebWmsGetlegendgraphicFormailist)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsGetlegendgraphicFormailist, self.txtMetadataWmsWebWmsKeywordlistVocabulary)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsKeywordlistVocabulary, self.txtMetadataWmsWebWmsKeywordlist)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsKeywordlist, self.txtMetadataWmsWebWmsLanguages)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsLanguages, self.txtMetadataWmsWebWmsLayerlimit)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsLayerlimit, self.txtMetadataWmsWebWmsRootlayerKeywordlist)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsRootlayerKeywordlist, self.txtMetadataWmsWebWmsRemoteSldMaxBytes)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsRemoteSldMaxBytes, self.txtMetadataWmsWebWmsServiceOnlineResource)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsServiceOnlineResource, self.txtMetadataWmsWebWmsResx)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsResx, self.txtMetadataWmsWebWmsResy)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsResy, self.txtMetadataWmsWebWmsRootlayerAbstract)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsRootlayerAbstract, self.txtMetadataWmsWebWmsRootlayerTitle)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsRootlayerTitle, self.txtMetadataWmsWebWmsTimeformat)
        MapfileExportDlg.setTabOrder(self.txtMetadataWmsWebWmsTimeformat, self.checkBoxWfs)
        MapfileExportDlg.setTabOrder(self.checkBoxWfs, self.txtMetadataWfsWebWfsEnableRequest)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsEnableRequest, self.txtMetadataWfsWebWfsTitle)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsTitle, self.txtMetadataWfsWebWfsOnlineresource)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsOnlineresource, self.txtMetadataWfsWebWfsSrs)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsSrs, self.txtMetadataWfsWebWfsAbstract)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsAbstract, self.txtMetadataWfsWebWfsAccessconstraints)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsAccessconstraints, self.txtMetadataWfsWebWfsEncoding)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsEncoding, self.txtMetadataWfsWebWfsFeatureCollection)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsFeatureCollection, self.txtMetadataWfsWebWfsFees)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsFees, self.txtMetadataWfsWebWfsKeywordlist)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsKeywordlist, self.txtMetadataWfsWebWfsGetcapabilitiesVersion)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsGetcapabilitiesVersion, self.txtMetadataWfsWebWfsNamespacePrefix)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsNamespacePrefix, self.txtMetadataWfsWebWfsMaxfeatures)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsMaxfeatures, self.txtMetadataWfsWebWfsServiceOnlineresource)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsServiceOnlineresource, self.txtMetadataWfsWebWfsNamespaceUri)
        MapfileExportDlg.setTabOrder(self.txtMetadataWfsWebWfsNamespaceUri, self.checkBoxWcs)
        MapfileExportDlg.setTabOrder(self.checkBoxWcs, self.txtMetadataWcsWebWcsEnableRequest)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsEnableRequest, self.txtMetadataWcsWebWcsLabel)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsLabel, self.txtMetadataWcsWebWcsAbstract)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsAbstract, self.txtMetadataWcsWebWcsAccessconstraints)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsAccessconstraints, self.txtMetadataWcsWebWcsDescription)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsDescription, self.txtMetadataWcsWebWcsKeywords)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsKeywords, self.txtMetadataWcsWebWcsFees)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsFees, self.txtMetadataWcsWebWcsMetadatalinkFormat)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsMetadatalinkFormat, self.txtMetadataWcsWebWcsMetadatalinkHref)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsMetadatalinkHref, self.txtMetadataWcsWebWcsMetadatalinkType)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsMetadatalinkType, self.txtMetadataWcsWebWcsName)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsName, self.txtMetadataWcsWebWcsServiceOnlineresource)
        MapfileExportDlg.setTabOrder(self.txtMetadataWcsWebWcsServiceOnlineresource, self.checkTmplFromFile)
        MapfileExportDlg.setTabOrder(self.checkTmplFromFile, self.txtTemplatePath)
        MapfileExportDlg.setTabOrder(self.txtTemplatePath, self.checkGenerateTmpl)
        MapfileExportDlg.setTabOrder(self.checkGenerateTmpl, self.templateTable)
        MapfileExportDlg.setTabOrder(self.templateTable, self.txtTmplHeaderPath)
        MapfileExportDlg.setTabOrder(self.txtTmplHeaderPath, self.txtTmplFooterPath)
        MapfileExportDlg.setTabOrder(self.txtTmplFooterPath, self.txtMapFontsetPath)
        MapfileExportDlg.setTabOrder(self.txtMapFontsetPath, self.checkCreateFontFile)
        MapfileExportDlg.setTabOrder(self.checkCreateFontFile, self.checkBoxForce)
        MapfileExportDlg.setTabOrder(self.checkBoxForce, self.checkBoxPartials)
        MapfileExportDlg.setTabOrder(self.checkBoxPartials, self.btnChooseTmplHeader)
        MapfileExportDlg.setTabOrder(self.btnChooseTmplHeader, self.scrollArea)
        MapfileExportDlg.setTabOrder(self.scrollArea, self.btnChooseTmplFooter)
        MapfileExportDlg.setTabOrder(self.btnChooseTmplFooter, self.scrollArea)
        MapfileExportDlg.setTabOrder(self.scrollArea, self.scrollArea)
        MapfileExportDlg.setTabOrder(self.scrollArea, self.btnChooseTemplate)
        MapfileExportDlg.setTabOrder(self.btnChooseTemplate, self.scrollArea)
        MapfileExportDlg.setTabOrder(self.scrollArea, self.btnChooseFile)
        MapfileExportDlg.setTabOrder(self.btnChooseFile, self.tabWiget)
        MapfileExportDlg.setTabOrder(self.tabWiget, self.tabWidget_2)

    def retranslateUi(self, MapfileExportDlg):
        MapfileExportDlg.setWindowTitle(_translate("MapfileExportDlg", "RT MapServer Exporter - Save project to MapFile", None))
        self.groupBox_2.setTitle(_translate("MapfileExportDlg", "Web", None))
        self.label6.setText(_translate("MapfileExportDlg", "Online resource URL", None))
        self.txtGeneralWebServerUrl.setToolTip(_translate("MapfileExportDlg", "The URL to the mapserver executable.\n"
"\n"
"For example: \n"
"http://my.host.com/cgi-bin/mapserv.exe", None))
        self.label6_5.setText(_translate("MapfileExportDlg", "Image path", None))
        self.txtGeneralWebImagePath.setToolTip(_translate("MapfileExportDlg", "Path to the temporary directory for writing temporary files and images. Must be writable by the user the web server is running as. Must end with a / or depending on your platform.", None))
        self.label6_4.setText(_translate("MapfileExportDlg", "Temporary path", None))
        self.label6_7.setText(_translate("MapfileExportDlg", "External graphic regexp", None))
        self.label6_6.setText(_translate("MapfileExportDlg", "Image URL", None))
        self.txtGeneralWebImageUrl.setToolTip(_translate("MapfileExportDlg", "Base URL for \"Image path\".\n"
"This is the URL that will take the web browser to \"Image path\" to get the images.", None))
        self.grpMap.setTitle(_translate("MapfileExportDlg", "Map", None))
        self.label5.setText(_translate("MapfileExportDlg", "Image type", None))
        self.label2.setText(_translate("MapfileExportDlg", "Width", None))
        self.label_9.setText(_translate("MapfileExportDlg", "PROJ LIB Folder*", None))
        self.label4.setText(_translate("MapfileExportDlg", "Units", None))
        self.label3.setText(_translate("MapfileExportDlg", "Height", None))
        self.label1.setText(_translate("MapfileExportDlg", "Name", None))
        self.label_30.setText(_translate("MapfileExportDlg", "Debug Level (0-5)", None))
        self.label_29.setText(_translate("MapfileExportDlg", "MS Error File Path", None))
        self.txtMapFilePath.setToolTip(_translate("MapfileExportDlg", "Name for the map file to be created from the QGIS project file", None))
        self.label.setText(_translate("MapfileExportDlg", "Map file", None))
        self.btnChooseFile.setText(_translate("MapfileExportDlg", "...", None))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tabGeneral), _translate("MapfileExportDlg", "General", None))
        self.groupBoxMetadataOws.setTitle(_translate("MapfileExportDlg", "Web", None))
        self.label_42.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Recommmended</span></p></body></html>", None))
        self.label_48.setText(_translate("MapfileExportDlg", "ows_updatesequence", None))
        self.label_22.setText(_translate("MapfileExportDlg", "ows_allowed_ip_list", None))
        self.label_23.setText(_translate("MapfileExportDlg", "ows_denied_ip_list", None))
        self.label_41.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Required</span></p></body></html>", None))
        self.label_5.setText(_translate("MapfileExportDlg", "ows_enable_request", None))
        self.label_8.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Optional</span></p></body></html>", None))
        self.label_7.setText(_translate("MapfileExportDlg", "ows_title", None))
        self.label_69.setText(_translate("MapfileExportDlg", "ows_sld_enabled", None))
        self.label_49.setText(_translate("MapfileExportDlg", "ows_schemas_location", None))
        self.label_4.setText(_translate("MapfileExportDlg", "ows_onlineresource", None))
        self.label_70.setText(_translate("MapfileExportDlg", "ows_http_max_age", None))
        self.label_6.setText(_translate("MapfileExportDlg", "ows_srs", None))
        self.checkBoxOws.setText(_translate("MapfileExportDlg", "Enable", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabMetadataOws), _translate("MapfileExportDlg", "OWS", None))
        self.groupBoxMetadataWms.setTitle(_translate("MapfileExportDlg", "Web", None))
        self.label_64.setText(_translate("MapfileExportDlg", "wms_service_onlineresource", None))
        self.label_66.setText(_translate("MapfileExportDlg", "wms_rootlayer_keywordlist", None))
        self.label_58.setText(_translate("MapfileExportDlg", "wms_onlineresource", None))
        self.label_19.setText(_translate("MapfileExportDlg", "wms_keywordlist", None))
        self.label_63.setText(_translate("MapfileExportDlg", "wms_timeformat", None))
        self.label_60.setText(_translate("MapfileExportDlg", "wms_resx", None))
        self.label_21.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Recommended</span></p></body></html>", None))
        self.label_46.setText(_translate("MapfileExportDlg", "wms_layerlimit", None))
        self.label_16.setText(_translate("MapfileExportDlg", "wms_fees", None))
        self.label_14.setText(_translate("MapfileExportDlg", "wms_encoding", None))
        self.label_18.setText(_translate("MapfileExportDlg", "wms_getlegendgraphic_formatlist", None))
        self.label_17.setText(_translate("MapfileExportDlg", "wms_getcapabilities_version", None))
        self.label_59.setText(_translate("MapfileExportDlg", "wms_remote_sld_max_bytes", None))
        self.label_11.setText(_translate("MapfileExportDlg", "wms_attribution_title", None))
        self.label_26.setText(_translate("MapfileExportDlg", "wms_keywordlist_vocabulary", None))
        self.label_67.setText(_translate("MapfileExportDlg", "wms_srs", None))
        self.label_10.setText(_translate("MapfileExportDlg", "wms_attribution_onlineresource", None))
        self.label_20.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Required</span></p></body></html>", None))
        self.label_24.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Optional</span></p></body></html>", None))
        self.label_68.setText(_translate("MapfileExportDlg", "wms_title", None))
        self.label_61.setText(_translate("MapfileExportDlg", "wms_rootlayer_abstract", None))
        self.label_65.setText(_translate("MapfileExportDlg", "wms_resy", None))
        self.label_12.setText(_translate("MapfileExportDlg", "wms_bbox_extended", None))
        self.label_13.setText(_translate("MapfileExportDlg", "wms_enable_request", None))
        self.label_25.setText(_translate("MapfileExportDlg", "wms_getmap_formatlist", None))
        self.label_15.setText(_translate("MapfileExportDlg", "wms_feature_info_mime_type", None))
        self.label_47.setText(_translate("MapfileExportDlg", "wms_languages", None))
        self.label_62.setText(_translate("MapfileExportDlg", "wms_rootlayer_title", None))
        self.checkBoxWms.setText(_translate("MapfileExportDlg", "Enable", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabMetadataWms), _translate("MapfileExportDlg", "WMS", None))
        self.groupBoxMetadataWfs.setTitle(_translate("MapfileExportDlg", "Web", None))
        self.label_151.setText(_translate("MapfileExportDlg", "wfs_feature_collection", None))
        self.label_251.setText(_translate("MapfileExportDlg", "wfs_namespace_prefix", None))
        self.label_27.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Required</span></p></body></html>", None))
        self.label_28.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Recommended</span></p></body></html>", None))
        self.label_471.setText(_translate("MapfileExportDlg", "wfs_srs", None))
        self.label_45.setText(_translate("MapfileExportDlg", "wfs_service_onlineresource", None))
        self.label_191.setText(_translate("MapfileExportDlg", "wfs_namespace_uri", None))
        self.label_111.setText(_translate("MapfileExportDlg", "wfs_accessconstraints", None))
        self.label_141.setText(_translate("MapfileExportDlg", "wfs_fees", None))
        self.label_161.setText(_translate("MapfileExportDlg", "wfs_getcapabilities_version", None))
        self.label_101.setText(_translate("MapfileExportDlg", "wfs_abstract", None))
        self.label_181.setText(_translate("MapfileExportDlg", "wfs_maxfeatures", None))
        self.label_121.setText(_translate("MapfileExportDlg", "wfs_encoding", None))
        self.label_261.setText(_translate("MapfileExportDlg", "wfs_onlineresource", None))
        self.label_131.setText(_translate("MapfileExportDlg", "wfs_enable_request", None))
        self.label_171.setText(_translate("MapfileExportDlg", "wfs_keywordlist", None))
        self.label_461.setText(_translate("MapfileExportDlg", "wfs_title", None))
        self.label_33.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Optional</span></p></body></html>", None))
        self.checkBoxWfs.setText(_translate("MapfileExportDlg", "Enable", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabMetadataWfs), _translate("MapfileExportDlg", "WFS", None))
        self.groupBoxMetadataWcs.setTitle(_translate("MapfileExportDlg", "Web", None))
        self.label_132.setText(_translate("MapfileExportDlg", "wcs_enable_request", None))
        self.label_36.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Required</span></p></body></html>", None))
        self.label_252.setText(_translate("MapfileExportDlg", "wcs_metadatalink_type", None))
        self.label_192.setText(_translate("MapfileExportDlg", "wcs_name", None))
        self.label_112.setText(_translate("MapfileExportDlg", "wcs_accessconstraints", None))
        self.label_142.setText(_translate("MapfileExportDlg", "wcs_fees", None))
        self.label_102.setText(_translate("MapfileExportDlg", "wcs_abstract", None))
        self.label_122.setText(_translate("MapfileExportDlg", "wcs_description", None))
        self.label_262.setText(_translate("MapfileExportDlg", "wcs_service_onlineresource", None))
        self.label_182.setText(_translate("MapfileExportDlg", "wcs_metadatalink_href", None))
        self.label_162.setText(_translate("MapfileExportDlg", "wcs_label", None))
        self.label_172.setText(_translate("MapfileExportDlg", "wcs_metadatalink_format", None))
        self.label_152.setText(_translate("MapfileExportDlg", "wcs_keywords", None))
        self.label_37.setText(_translate("MapfileExportDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Optional</span></p></body></html>", None))
        self.checkBoxWcs.setText(_translate("MapfileExportDlg", "Enable", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabMetadataWcs), _translate("MapfileExportDlg", "WCS", None))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tabMatadata), _translate("MapfileExportDlg", "Metadata", None))
        self.checkTmplFromFile.setToolTip(_translate("MapfileExportDlg", "Forces labels on, regardless of collisions. Available only for cached labels.", None))
        self.checkTmplFromFile.setText(_translate("MapfileExportDlg", "Template from file", None))
        self.txtTemplatePath.setToolTip(_translate("MapfileExportDlg", "Name for the map file to be created from the QGIS project file", None))
        self.btnChooseTemplate.setText(_translate("MapfileExportDlg", "...", None))
        self.checkGenerateTmpl.setToolTip(_translate("MapfileExportDlg", "Forces labels on, regardless of collisions. Available only for cached labels.", None))
        self.checkGenerateTmpl.setText(_translate("MapfileExportDlg", "Autogenerate template for layers", None))
        self.label_2.setText(_translate("MapfileExportDlg", "Header", None))
        self.txtTmplHeaderPath.setToolTip(_translate("MapfileExportDlg", "Name for the map file to be created from the QGIS project file", None))
        self.btnChooseTmplHeader.setText(_translate("MapfileExportDlg", "...", None))
        self.label_3.setText(_translate("MapfileExportDlg", "Footer", None))
        self.txtTmplFooterPath.setToolTip(_translate("MapfileExportDlg", "Name for the map file to be created from the QGIS project file", None))
        self.btnChooseTmplFooter.setText(_translate("MapfileExportDlg", "...", None))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tabTemplate), _translate("MapfileExportDlg", "Template", None))
        self.grpOptions.setTitle(_translate("MapfileExportDlg", "Label options", None))
        self.checkBoxForce.setToolTip(_translate("MapfileExportDlg", "Forces labels on, regardless of collisions. Available only for cached labels.", None))
        self.checkBoxForce.setText(_translate("MapfileExportDlg", "Force", None))
        self.checkBoxPartials.setToolTip(_translate("MapfileExportDlg", "Can text run off the edge of the map?", None))
        self.checkBoxPartials.setText(_translate("MapfileExportDlg", "Partials", None))
        self.groupBox_3.setTitle(_translate("MapfileExportDlg", "Fontset", None))
        self.label6_3.setText(_translate("MapfileExportDlg", "Path", None))
        self.txtMapFontsetPath.setToolTip(_translate("MapfileExportDlg", "path", None))
        self.checkCreateFontFile.setToolTip(_translate("MapfileExportDlg", "Forces labels on, regardless of collisions. Available only for cached labels.", None))
        self.checkCreateFontFile.setText(_translate("MapfileExportDlg", "Generate used fonts file", None))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tabAdvanced), _translate("MapfileExportDlg", "Advanced", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MapfileExportDlg = QtGui.QDialog()
    ui = Ui_MapfileExportDlg()
    ui.setupUi(MapfileExportDlg)
    MapfileExportDlg.show()
    sys.exit(app.exec_())

